name: "CI"
env:
  STORE_PATH:

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out changes
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Running Test
        run: pnpm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checking out changes
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Building Package
        run: pnpm run build
