name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checking out changes
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test

  build:
    name: build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checking out changes
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
